---

- name: Install Java (required by Jenkins)
  apt:
    name: "{{ java_package }}"
    state: present
    update_cache: yes

- name: Add Jenkins GPG key
  apt_key:
    url: "{{ jenkins_key_url }}"
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "{{ jenkins_repo }}"
    state: present

- name: Install Jenkins
  apt:
    name: "{{ jenkins_package }}"
    state: present
    update_cache: yes
  notify: restart jenkins

- name: Ensure Jenkins is running and enabled
  service:
    name: "{{ jenkins_package }}"
    state: started
    enabled: true

- name: Verify Jenkins status
  command: systemctl status jenkins
  register: jenkins_status
  changed_when: false