---
- name: Install a secure MySQL database
  hosts: databases
  become: true

  vars_files:
    - ./vaultvars.yaml

  tasks:
    - name: Install mysql
      apt:
        name: mysql-server
        state: latest
    
    - name: Confirmation
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install Python MySQL driver
      apt:
        name: python3-pymysql
        state: present

    - name: Create database
      mysql_db:
        name: iVolve
        state: present
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create database user 
      mysql_user:
        name: "{{ ivolve_db_user }}"
        password: "{{ ivolve_db_password }}"
        priv: "*.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
