all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 10.245.184.181
        web2:
          ansible_host: 10.245.184.233
    database:
      hosts:
        db1:
          ansible_host: 10.245.184.150


  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/abdelrhman/.ssh/id_rsa
