- name: ping the dynamic inventory
  hosts: AZ_2a
  
  tasks:
    - name: The ping module
      ping:

    - name: Create a directory
      ansible.builtin.file:
        path: /home/ubuntu/
        state: directory
        mode: '0755' 